apiVersion: v1
kind: PersistentVolume
metadata:
  name: home-pv
spec:
    capacity:
        storage: 10Gi
    volumeMode: Filesystem
    accessModes:
        - ReadWriteOnce
    persistentVolumeReclaimPolicy: Retain
    storageClassName: hostpath-remain
    hostPath:
      path: /Users/mp/k8sVolumes/home

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: home-pvc
spec:
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
          storage: 10Gi
    storageClassName: hostpath-remain