apiVersion: v1
kind: Pod
metadata:
  name: workbox
spec:
  containers:
  - name: workbox
    image: amazonlinux:2
    command: ["/bin/bash", "-c", "--"]
    args: ["while true; do sleep 30; done;"]
    volumeMounts:
    - mountPath: /data
      name: data-volume
  volumes:
  - name: data-volume
    persistentVolumeClaim:
      claimName: data-pvc

# kubectl apply -f workbox.yaml
# kubectl exec -it workbox -- /bin/bash